# Generated by Django 5.1.15 on 2026-07-07 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('contenido_json', models.JSONField(blank=True, null=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('dislikes_count', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('barbero', models.ForeignKey(db_column='barbero_id', on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'publicaciones',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_realizados', to='usuarios.usuario')),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='publicaciones.publicacion')),
            ],
            options={
                'db_table': 'comentarios',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='publicaciones.publicacion')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='reacciones_realizadas', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'reacciones',
                'constraints': [models.UniqueConstraint(fields=('publicacion', 'usuario'), name='unique_publicacion_usuario')],
            },
        ),
    ]
