# Generated by Django 5.1.15 on 2026-07-08 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_REEMBOLSO', 'Pendiente de reembolso'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20)),
                ('mercadopago_id', models.CharField(blank=True, max_length=255, null=True)),
                ('preference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('cita', models.ForeignKey(db_column='cita_id', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='citas.cita')),
            ],
            options={
                'db_table': 'pagos',
                'ordering': ['-createdAt'],
            },
        ),
    ]
