# Generated by Django 5.1.15 on 2026-07-07 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('barbero', models.ForeignKey(db_column='barbero_id', on_delete=django.db.models.deletion.CASCADE, related_name='citas_como_barbero', to='usuarios.usuario')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='citas_como_cliente', to='usuarios.usuario')),
                ('servicio', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='servicios.servicio')),
            ],
            options={
                'db_table': 'citas',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
