# Generated by Django 5.1.15 on 2026-07-09 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion_total',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios_adicionales',
            field=models.ManyToManyField(blank=True, related_name='citas_adicionales', to='servicios.servicio'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='citas_principales', to='servicios.servicio'),
        ),
    ]
